plugins:
  # - name

  # - name: false
  # - name: true

  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype: true
  - removeXMLProcInst: false
  - removeComments: false
  - removeMetadata: true
  - removeXMLNS: false
  - removeEditorsNSData: true
  - cleanupAttrs: true
  - inlineStyles: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - cleanupIDs: false
  - prefixIds: false
  - removeRasterImages: false
  - removeUselessDefs: true
  - cleanupNumericValues: true
  - cleanupListOfValues: true
  - convertColors: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: false
  - cleanupEnableBackground: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: false
  - convertEllipseToCircle: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: false
  - convertPathData:
      floatPrecision: 2
      transformPrecision: 4
  - convertTransform: true
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - mergePaths: false
  - removeUnusedNS: true
  - sortAttrs: true
  - sortDefsChildren: true
  - removeTitle: true
  - removeDesc: true
  - removeDimensions: false
  - removeAttrs:
      attrs: '(clip-rule|fill-rule|stroke-linejoin|stroke-miterlimit|stroke-linecap)'
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - removeStyleElement: true
  - removeScriptElement: true
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: true
  - reusePaths: false

js2svg:
 pretty: true
 indent: 2